<%@ page contentType="text/html; charset=utf-8" language="java" import="java.sql.*" errorPage="" %>
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title>上品折扣网 - 实体店应季正品保障，全网底价折扣</title>
<link href="http://images.shopin.net/s/css/reset.css" rel="stylesheet" type="text/css">
<link href="http://images.shopin.net/s/css/layout.css" rel="stylesheet" type="text/css">
<link href="http://images.shopin.net/s/css/cart.css" rel="stylesheet" type="text/css">
</head>

<body><div class="in oz shopin">
		<div class="breadCrumbs"><span class="myshopin">帮助中心</span> > <a href="discost.html">配送方式</a> > 运费及送达区域</div>
</div>
<div id="container" class="in oz shopin">
		<div class="leftmenu">
				<div class="leftbox">
						<dl>
								<dt>关于上品</dt>
								<dd><a href="aboutus.html">公司简介</a></dd>
								<dd><a href="store.html">各门店介绍</a></dd>
								<dd><a href="job.html">诚聘英才</a></dd>
								<dd><a href="contact.html">联系我们</a></dd>
						</dl>
						<dl>
								<dt>新手上路</dt>
								<dd><a href="newreg.html">新用户注册</a></dd>
								<dd><a href="cartstep.html">购物流程</a></dd>
								<dd><a href="payfor.html">支付方式</a></dd>
								<dd><a href="size.html">标准尺码表参考</a></dd>
						</dl>
						<dl>
								<dt>支付方式</dt>
								<dd><a href="webpay.html">网上支付</a></dd>
								<dd><a href="webhelp.html">网上支付帮助</a></dd>
								<dd><a href="shopincard.html">购物劵使用说明</a></dd>
								<dd><a href="fapiao.html">发票制度说明</a></dd>
						</dl>
						<dl>
								<dt>配送方式</dt>
								<dd><a href="discost.html">配送费收取标准</a></dd>
								<dd class="fb"><a href="distime.html">配送时间和范围</a></dd>
								<dd><a href="distrib.html">跟踪配送信息</a></dd>
								<dd><a href="inspect.html">验货与签收</a></dd>
						</dl>
						<dl>
								<dt>退货服务</dt>
								<dd><a href="policy.html">退货政策</a></dd>
								<dd><a href="flowpath.html">退货流程</a></dd>
								<dd><a href="matter.html">退货注意事项</a></dd>
								<dd><a href="return.html">退货方式及时间</a></dd>
								<dd><a href="refund.html">货到付款退款说明</a></dd>
						</dl>
						<dl>
								<dt>客服中心</dt>
								<dd><a href="question.html">常见问题</a></dd>
								<dd><a href="http://www.shopin.net/msg/common/1.html" target="_blank">在线留言</a></dd>
								<dd><a href="customer.html">联系客服</a></dd>
						</dl>
				</div>
		</div>
		<div class="rightlist helplist">
				<h2>运费及送达区域</h2>
				<div class="helpCon">
						<strong>【快递方式】可送达地区及运费标准</strong><br>
						<table width="100%" border="0" cellspacing="0" cellpadding="0" class="helpbox tc">
				<tr>
				<th>省份</th>
				<th>区市</th>
				<th>运费（元/单）</th>
				</tr>
				
				<tr>
				<td rowspan="18" align="center">北京</td>
				<td>朝阳区</td>
				<td rowspan="8">6</td>
				</tr>
				<tr>
				<td>海淀区</td>
				</tr>
				<tr>
				<td>崇文区</td>
				</tr>
				<tr>
				<td>丰台区</td>
				</tr>
				<tr>
				<td>东城区</td>
				</tr>
				<tr>
				<td>石景山区</td>
				</tr>
				<tr>
				<td>西城区</td>
				</tr>
				<tr>
				<td>宣武区</td>
				</tr>
				<tr>
				<td>平谷区</td>
				<td rowspan="10">10</td>
				</tr>
				<tr>
				<td>怀柔区</td>
				</tr>
				<tr>
				<td>密云区</td>
				</tr>
				<tr>
				<td>延庆区</td>
				</tr>
				<tr>
				<td>通州区</td>
				</tr>
				<tr>
				<td>房山区</td>
				</tr>
				<tr>
				<td>门头沟区</td>
				</tr>
				<tr>
				<td>昌平区</td>
				</tr>
				<tr>
				<td>顺义区</td>
				</tr>
				<tr>
				<td>大兴区</td>
				</tr>
				<tr>
				<td rowspan="17">安徽</td>
				<td>安庆</td>
				<td rowspan="17">14</td>
				</tr>
				<tr>
				<td>蚌埠</td>
				</tr>
				<tr>
				<td>巢湖</td>
				</tr>
				<tr>
				<td>池州</td>
				</tr>
				<tr>
				<td>滁州</td>
				</tr>
				<tr>
				<td>阜阳</td>
				</tr>
				<tr>
				<td>合肥</td>
				</tr>
				<tr>
				<td>淮北</td>
				</tr>
				<tr>
				<td>淮南</td>
				</tr>
				<tr>
				<td>黄山</td>
				</tr>
				<tr>
				<td>六安</td>
				</tr>
				<tr>
				<td>马鞍山</td>
				</tr>
				<tr>
				<td>宿州</td>
				</tr>
				<tr>
				<td>铜陵</td>
				</tr>
				<tr>
				<td>芜湖</td>
				</tr>
				<tr>
				<td>宣城</td>
				</tr>
				<tr>
				<td>亳州</td>
				</tr>
				<tr>
				<td rowspan="9">福建</td>
				<td>福州</td>
				<td rowspan="9">16</td>
				</tr>
				<tr>
				<td>龙岩</td>
				</tr>
				<tr>
				<td>南平</td>
				</tr>
				<tr>
				<td>宁德</td>
				</tr>
				<tr>
				<td>莆田</td>
				</tr>
				<tr>
				<td>泉州</td>
				</tr>
				<tr>
				<td>三明</td>
				</tr>
				<tr>
				<td>厦门</td>
				</tr>
				<tr>
				<td>漳州</td>
				</tr>
				<tr>
				<td rowspan="11">河北</td>
				<td>张家口</td>
				<td rowspan="11">12</td>
				</tr>
				<tr>
				<td>保定</td>
				</tr>
				<tr>
				<td>沧州</td>
				</tr>
				<tr>
				<td>承德</td>
				</tr>
				<tr>
				<td>邯郸</td>
				</tr>
				<tr>
				<td>衡水</td>
				</tr>
				<tr>
				<td>廊坊</td>
				</tr>
				<tr>
				<td>秦皇岛</td>
				</tr>
				<tr>
				<td>石家庄</td>
				</tr>
				<tr>
				<td>唐山</td>
				</tr>
				<tr>
				<td>邢台</td>
				</tr>
				<tr>
				<td rowspan="18">河南</td>
				<td>安阳</td>
				<td rowspan="38">14</td>
				</tr>
				<tr>
				<td>鹤壁</td>
				</tr>
				<tr>
				<td>济源</td>
				</tr>
				<tr>
				<td>焦作</td>
				</tr>
				<tr>
				<td>开封</td>
				</tr>
				<tr>
				<td>洛阳</td>
				</tr>
				<tr>
				<td>南阳</td>
				</tr>
				<tr>
				<td>平顶山</td>
				</tr>
				<tr>
				<td>三门峡</td>
				</tr>
				<tr>
				<td>商丘</td>
				</tr>
				<tr>
				<td>新乡</td>
				</tr>
				<tr>
				<td>信阳</td>
				</tr>
				<tr>
				<td>许昌</td>
				</tr>
				<tr>
				<td>郑州</td>
				</tr>
				<tr>
				<td>周口</td>
				</tr>
				<tr>
				<td>驻马店</td>
				</tr>
				<tr>
				<td>漯河</td>
				</tr>
				<tr>
				<td>濮阳</td>
				</tr>
				<tr>
				<td rowspan="11">黑龙江</td>
				<td>大庆</td>
				</tr>
				<tr>
				<td>哈尔滨</td>
				</tr>
				<tr>
				<td>鹤岗</td>
				</tr>
				<tr>
				<td>黑河</td>
				</tr>
				<tr>
				<td>鸡西</td>
				</tr>
				<tr>
				<td>佳木斯</td>
				</tr>
				<tr>
				<td>牡丹江</td>
				</tr>
				<tr>
				<td>七台河</td>
				</tr>
				<tr>
				<td>齐齐哈尔</td>
				</tr>
				<tr>
				<td>绥化</td>
				</tr>
				<tr>
				<td>伊春</td>
				</tr>
				<tr>
				<td rowspan="9">吉林</td>
				<td>白城</td>
				</tr>
				<tr>
				<td>白山</td>
				</tr>
				<tr>
				<td>长春</td>
				</tr>
				<tr>
				<td>吉林</td>
				</tr>
				<tr>
				<td>辽源</td>
				</tr>
				<tr>
				<td>四平</td>
				</tr>
				<tr>
				<td>松原</td>
				</tr>
				<tr>
				<td>通化</td>
				</tr>
				<tr>
				<td>延边朝鲜族自治州</td>
				</tr>
				<tr>
				<td rowspan="13">江苏</td>
				<td>常州</td>
				<td rowspan="13">14</td>
				</tr>
				<tr>
				<td>淮安</td>
				</tr>
				<tr>
				<td>连云港</td>
				</tr>
				<tr>
				<td>南京</td>
				</tr>
				<tr>
				<td>南通</td>
				</tr>
				<tr>
				<td>苏州</td>
				</tr>
				<tr>
				<td>宿迁</td>
				</tr>
				<tr>
				<td>泰州</td>
				</tr>
				<tr>
				<td>无锡</td>
				</tr>
				<tr>
				<td>徐州</td>
				</tr>
				<tr>
				<td>盐城</td>
				</tr>
				<tr>
				<td>扬州</td>
				</tr>
				<tr>
				<td>镇江</td>
				</tr>
				<tr>
				<td rowspan="10">江西</td>
				<td>抚州</td>
				<td rowspan="10">14</td>
				</tr>
				<tr>
				<td>赣州</td>
				</tr>
				<tr>
				<td>吉安</td>
				</tr>
				<tr>
				<td>景德镇</td>
				</tr>
				<tr>
				<td>九江</td>
				</tr>
				<tr>
				<td>南昌</td>
				</tr>
				<tr>
				<td>萍乡</td>
				</tr>
				<tr>
				<td>上饶</td>
				</tr>
				<tr>
				<td>新余</td>
				</tr>
				<tr>
				<td>宜春</td>
				</tr>
				<tr>
				<td rowspan="11">辽宁</td>
				<td>本溪</td>
				<td rowspan="11">14</td>
				</tr>
				<tr>
				<td>鞍山</td>
				</tr>
				<tr>
				<td>大连</td>
				</tr>
				<tr>
				<td>丹东</td>
				</tr>
				<tr>
				<td>葫芦岛</td>
				</tr>
				<tr>
				<td>锦州</td>
				</tr>
				<tr>
				<td>辽阳</td>
				</tr>
				<tr>
				<td>盘锦</td>
				</tr>
				<tr>
				<td>沈阳</td>
				</tr>
				<tr>
				<td>铁岭</td>
				</tr>
				<tr>
				<td>营口</td>
				</tr>
				<tr>
				<td rowspan="17">四川</td>
				<td>成都</td>
				<td rowspan="17">16</td>
				</tr>
				<tr>
				<td>达州</td>
				</tr>
				<tr>
				<td>德阳</td>
				</tr>
				<tr>
				<td>广安</td>
				</tr>
				<tr>
				<td>广元</td>
				</tr>
				<tr>
				<td>乐山</td>
				</tr>
				<tr>
				<td>眉山</td>
				</tr>
				<tr>
				<td>绵阳</td>
				</tr>
				<tr>
				<td>南充</td>
				</tr>
				<tr>
				<td>内江</td>
				</tr>
				<tr>
				<td>攀枝花</td>
				</tr>
				<tr>
				<td>遂宁</td>
				</tr>
				<tr>
				<td>雅安</td>
				</tr>
				<tr>
				<td>宜宾</td>
				</tr>
				<tr>
				<td>资阳</td>
				</tr>
				<tr>
				<td>自贡</td>
				</tr>
				<tr>
				<td>泸州</td>
				</tr>
				<tr>
				<td rowspan="17">天津</td>
				<td>宝坻区</td>
				<td rowspan="17">12</td>
				</tr>
				<tr>
				<td>北辰区</td>
				</tr>
				<tr>
				<td>大港区</td>
				</tr>
				<tr>
				<td>东丽区</td>
				</tr>
				<tr>
				<td>汉沽区</td>
				</tr>
				<tr>
				<td>和平区</td>
				</tr>
				<tr>
				<td>河北区</td>
				</tr>
				<tr>
				<td>河东区</td>
				</tr>
				<tr>
				<td>河西区</td>
				</tr>
				<tr>
				<td>红桥区</td>
				</tr>
				<tr>
				<td>蓟县</td>
				</tr>
				<tr>
				<td>津南区</td>
				</tr>
				<tr>
				<td>静海县</td>
				</tr>
				<tr>
				<td>南开区</td>
				</tr>
				<tr>
				<td>塘沽区</td>
				</tr>
				<tr>
				<td>武清区</td>
				</tr>
				<tr>
				<td>西青区</td>
				</tr>
				<tr>
				<td rowspan="40">重庆</td>
				<td>秀山土家族苗族自治县</td>
				<td rowspan="40">16</td>
				</tr>
				<tr>
				<td>巴南区</td>
				</tr>
				<tr>
				<td>北碚区</td>
				</tr>
				<tr>
				<td>长寿区</td>
				</tr>
				<tr>
				<td>城口县</td>
				</tr>
				<tr>
				<td>大渡口区</td>
				</tr>
				<tr>
				<td>大足县</td>
				</tr>
				<tr>
				<td>垫江县</td>
				</tr>
				<tr>
				<td>丰都县</td>
				</tr>
				<tr>
				<td>奉节县</td>
				</tr>
				<tr>
				<td>涪陵区</td>
				</tr>
				<tr>
				<td>合川市</td>
				</tr>
				<tr>
				<td>江北区</td>
				</tr>
				<tr>
				<td>江津市</td>
				</tr>
				<tr>
				<td>九龙坡区</td>
				</tr>
				<tr>
				<td>开县</td>
				</tr>
				<tr>
				<td>梁平县</td>
				</tr>
				<tr>
				<td>南岸区</td>
				</tr>
				<tr>
				<td>南川市</td>
				</tr>
				<tr>
				<td>彭水苗族土家族自治县</td>
				</tr>
				<tr>
				<td>黔江区</td>
				</tr>
				<tr>
				<td>荣昌县</td>
				</tr>
				<tr>
				<td>沙坪坝区</td>
				</tr>
				<tr>
				<td>石柱土家族自治县</td>
				</tr>
				<tr>
				<td>双桥区</td>
				</tr>
				<tr>
				<td>铜梁县</td>
				</tr>
				<tr>
				<td>万盛区</td>
				</tr>
				<tr>
				<td>万州区</td>
				</tr>
				<tr>
				<td>巫山县</td>
				</tr>
				<tr>
				<td>巫溪县</td>
				</tr>
				<tr>
				<td>武隆县</td>
				</tr>
				<tr>
				<td>永川市</td>
				</tr>
				<tr>
				<td>酉阳土家族苗族自治县</td>
				</tr>
				<tr>
				<td>渝北区</td>
				</tr>
				<tr>
				<td>渝中区</td>
				</tr>
				<tr>
				<td>云阳县</td>
				</tr>
				<tr>
				<td>忠县</td>
				</tr>
				<tr>
				<td>潼南县</td>
				</tr>
				<tr>
				<td>璧山县</td>
				</tr>
				<tr>
				<td>綦江县</td>
				</tr>
				<tr>
				<td rowspan="14">甘肃</td>
				<td>甘南藏族</td>
				<td rowspan="14">22</td>
				</tr>
				<tr>
				<td>临夏回族</td>
				</tr>
				<tr>
				<td>白银</td>
				</tr>
				<tr>
				<td>定西</td>
				</tr>
				<tr>
				<td>嘉峪关</td>
				</tr>
				<tr>
				<td>金昌</td>
				</tr>
				<tr>
				<td>酒泉</td>
				</tr>
				<tr>
				<td>兰州</td>
				</tr>
				<tr>
				<td>陇南</td>
				</tr>
				<tr>
				<td>平凉</td>
				</tr>
				<tr>
				<td>庆阳</td>
				</tr>
				<tr>
				<td>天水</td>
				</tr>
				<tr>
				<td>武威</td>
				</tr>
				<tr>
				<td>张掖</td>
				</tr>
				<tr>
				<td rowspan="21">广东</td>
				<td>珠海</td>
				<td rowspan="21">12</td>
				</tr>
				<tr>
				<td>潮州</td>
				</tr>
				<tr>
				<td>东莞</td>
				</tr>
				<tr>
				<td>佛山</td>
				</tr>
				<tr>
				<td>广州</td>
				</tr>
				<tr>
				<td>河源</td>
				</tr>
				<tr>
				<td>惠州</td>
				</tr>
				<tr>
				<td>江门</td>
				</tr>
				<tr>
				<td>揭阳</td>
				</tr>
				<tr>
				<td>茂名</td>
				</tr>
				<tr>
				<td>梅州</td>
				</tr>
				<tr>
				<td>清远</td>
				</tr>
				<tr>
				<td>汕头</td>
				</tr>
				<tr>
				<td>汕尾</td>
				</tr>
				<tr>
				<td>韶关</td>
				</tr>
				<tr>
				<td>深圳</td>
				</tr>
				<tr>
				<td>阳江</td>
				</tr>
				<tr>
				<td>云浮</td>
				</tr>
				<tr>
				<td>湛江</td>
				</tr>
				<tr>
				<td>肇庆</td>
				</tr>
				<tr>
				<td>中山</td>
				</tr>
				<tr>
				<td rowspan="14">广西</td>
				<td>百色</td>
				<td rowspan="20">22</td>
				</tr>
				<tr>
				<td>北海</td>
				</tr>
				<tr>
				<td>崇左</td>
				</tr>
				<tr>
				<td>防城港</td>
				</tr>
				<tr>
				<td>桂林</td>
				</tr>
				<tr>
				<td>贵港</td>
				</tr>
				<tr>
				<td>河池</td>
				</tr>
				<tr>
				<td>贺州</td>
				</tr>
				<tr>
				<td>来宾</td>
				</tr>
				<tr>
				<td>柳州</td>
				</tr>
				<tr>
				<td>南宁</td>
				</tr>
				<tr>
				<td>钦州</td>
				</tr>
				<tr>
				<td>梧州</td>
				</tr>
				<tr>
				<td>玉林</td>
				</tr>
				<tr>
				<td rowspan="3">贵州</td>
				<td>贵阳</td>
				</tr>
				<tr>
				<td>六盘水</td>
				</tr>
				<tr>
				<td>遵义</td>
				</tr>
				<tr>
				<td rowspan="3">海南</td>
				<td>海口</td>
				</tr>
				<tr>
				<td>琼海</td>
				</tr>
				<tr>
				<td>三亚</td>
				</tr>
				<tr>
				<td rowspan="13">湖北</td>
				<td>咸宁</td>
				<td rowspan="13">16</td>
				</tr>
				<tr>
				<td>鄂州</td>
				</tr>
				<tr>
				<td>黄冈</td>
				</tr>
				<tr>
				<td>黄石</td>
				</tr>
				<tr>
				<td>潜江</td>
				</tr>
				<tr>
				<td>十堰</td>
				</tr>
				<tr>
				<td>随州</td>
				</tr>
				<tr>
				<td>天门</td>
				</tr>
				<tr>
				<td>武汉</td>
				</tr>
				<tr>
				<td>仙桃</td>
				</tr>
				<tr>
				<td>襄樊</td>
				</tr>
				<tr>
				<td>孝感</td>
				</tr>
				<tr>
				<td>宜昌</td>
				</tr>
				<tr>
				<td rowspan="14">湖南</td>
				<td>湘西土家</td>
				<td rowspan="14">16</td>
				</tr>
				<tr>
				<td>常德</td>
				</tr>
				<tr>
				<td>长沙</td>
				</tr>
				<tr>
				<td>郴州</td>
				</tr>
				<tr>
				<td>衡阳</td>
				</tr>
				<tr>
				<td>怀化</td>
				</tr>
				<tr>
				<td>娄底</td>
				</tr>
				<tr>
				<td>邵阳</td>
				</tr>
				<tr>
				<td>湘潭</td>
				</tr>
				<tr>
				<td>益阳</td>
				</tr>
				<tr>
				<td>永州</td>
				</tr>
				<tr>
				<td>岳阳</td>
				</tr>
				<tr>
				<td>张家界</td>
				</tr>
				<tr>
				<td>株洲</td>
				</tr>
				<tr>
				<td rowspan="12">内蒙古</td>
				<td>阿拉善盟</td>
				<td rowspan="12">22</td>
				</tr>
				<tr>
				<td>巴彦淖尔</td>
				</tr>
				<tr>
				<td>包头</td>
				</tr>
				<tr>
				<td>赤峰</td>
				</tr>
				<tr>
				<td>鄂尔多斯</td>
				</tr>
				<tr>
				<td>呼和浩特</td>
				</tr>
				<tr>
				<td>呼伦贝尔</td>
				</tr>
				<tr>
				<td>通辽</td>
				</tr>
				<tr>
				<td>乌海</td>
				</tr>
				<tr>
				<td>乌兰察布</td>
				</tr>
				<tr>
				<td>锡林郭勒盟</td>
				</tr>
				<tr>
				<td>兴安盟</td>
				</tr>
				<tr>
				<td rowspan="2">宁夏</td>
				<td>石嘴山</td>
				<td rowspan="2">22</td>
				</tr>
				<tr>
				<td>银川</td>
				</tr>
				<tr>
				<td>青海</td>
				<td>西宁</td>
				<td>22</td>
				</tr>
				<tr>
				<td rowspan="17">山东</td>
				<td>济南</td>
				<td rowspan="17">14</td>
				</tr>
				<tr>
				<td>济宁</td>
				</tr>
				<tr>
				<td>莱芜</td>
				</tr>
				<tr>
				<td>聊城</td>
				</tr>
				<tr>
				<td>临沂</td>
				</tr>
				<tr>
				<td>青岛</td>
				</tr>
				<tr>
				<td>日照</td>
				</tr>
				<tr>
				<td>泰安</td>
				</tr>
				<tr>
				<td>威海</td>
				</tr>
				<tr>
				<td>潍坊</td>
				</tr>
				<tr>
				<td>烟台</td>
				</tr>
				<tr>
				<td>枣庄</td>
				</tr>
				<tr>
				<td>淄博</td>
				</tr>
				<tr>
				<td>滨州</td>
				</tr>
				<tr>
				<td>德州</td>
				</tr>
				<tr>
				<td>东营</td>
				</tr>
				<tr>
				<td>菏泽</td>
				</tr>
				<tr>
				<td rowspan="11">山西</td>
				<td>长治</td>
				<td rowspan="11">16</td>
				</tr>
				<tr>
				<td>大同</td>
				</tr>
				<tr>
				<td>晋城</td>
				</tr>
				<tr>
				<td>晋中</td>
				</tr>
				<tr>
				<td>临汾</td>
				</tr>
				<tr>
				<td>吕梁</td>
				</tr>
				<tr>
				<td>朔州</td>
				</tr>
				<tr>
				<td>太原</td>
				</tr>
				<tr>
				<td>忻州</td>
				</tr>
				<tr>
				<td>阳泉</td>
				</tr>
				<tr>
				<td>运城</td>
				</tr>
				<tr>
				<td rowspan="10">陕西</td>
				<td>安康</td>
				<td rowspan="10">16</td>
				</tr>
				<tr>
				<td>宝鸡</td>
				</tr>
				<tr>
				<td>汉中</td>
				</tr>
				<tr>
				<td>商洛</td>
				</tr>
				<tr>
				<td>铜川</td>
				</tr>
				<tr>
				<td>渭南</td>
				</tr>
				<tr>
				<td>西安</td>
				</tr>
				<tr>
				<td>咸阳</td>
				</tr>
				<tr>
				<td>延安</td>
				</tr>
				<tr>
				<td>榆林</td>
				</tr>
				<tr>
				<td rowspan="19">上海</td>
				<td>金山区</td>
				<td rowspan="19">12</td>
				</tr>
				<tr>
				<td>静安区</td>
				</tr>
				<tr>
				<td>卢湾区</td>
				</tr>
				<tr>
				<td>南汇区</td>
				</tr>
				<tr>
				<td>普陀区</td>
				</tr>
				<tr>
				<td>浦东新区</td>
				</tr>
				<tr>
				<td>青浦区</td>
				</tr>
				<tr>
				<td>松江区</td>
				</tr>
				<tr>
				<td>徐汇区</td>
				</tr>
				<tr>
				<td>杨浦区</td>
				</tr>
				<tr>
				<td>闸北区</td>
				</tr>
				<tr>
				<td>闵行区</td>
				</tr>
				<tr>
				<td>宝山区</td>
				</tr>
				<tr>
				<td>长宁区</td>
				</tr>
				<tr>
				<td>崇明县</td>
				</tr>
				<tr>
				<td>奉贤区</td>
				</tr>
				<tr>
				<td>虹口区</td>
				</tr>
				<tr>
				<td>黄浦区</td>
				</tr>
				<tr>
				<td>嘉定区</td>
				</tr>
				<tr>
				<td rowspan="11">云南</td>
				<td>保山</td>
				<td rowspan="11">22</td>
				</tr>
				<tr>
				<td>昆明</td>
				</tr>
				<tr>
				<td>丽江</td>
				</tr>
				<tr>
				<td>临沧</td>
				</tr>
				<tr>
				<td>曲靖</td>
				</tr>
				<tr>
				<td>玉溪</td>
				</tr>
				<tr>
				<td>昭通</td>
				</tr>
				<tr>
				<td>楚雄彝族</td>
				</tr>
				<tr>
				<td>德宏傣族</td>
				</tr>
				<tr>
				<td>文山壮族</td>
				</tr>
				<tr>
				<td>大理白族</td>
				</tr>
				<tr>
				<td rowspan="11">浙江</td>
				<td>杭州</td>
				<td rowspan="11">14</td>
				</tr>
				<tr>
				<td>嘉兴</td>
				</tr>
				<tr>
				<td>金华</td>
				</tr>
				<tr>
				<td>丽水</td>
				</tr>
				<tr>
				<td>宁波</td>
				</tr>
				<tr>
				<td>绍兴</td>
				</tr>
				<tr>
				<td>台州</td>
				</tr>
				<tr>
				<td>温州</td>
				</tr>
				<tr>
				<td>舟山</td>
				</tr>
				<tr>
				<td>衢州</td>
				</tr>
				<tr>
				<td>湖州</td>
				</tr>
				<tr>
				<td rowspan="7">西藏</td>
				<td>拉萨</td>
				<td rowspan="25">38</td>
				</tr>
				<tr>
				<td>日喀则</td>
				</tr>
				<tr>
				<td>山南</td>
				</tr>
				<tr>
				<td>阿里</td>
				</tr>
				<tr>
				<td>昌都</td>
				</tr>
				<tr>
				<td>林芝</td>
				</tr>
				<tr>
				<td>那曲</td>
				</tr>
				<tr>
				<td rowspan="18">新疆</td>
				<td>阿拉尔</td>
				</tr>
				<tr>
				<td>克拉玛依</td>
				</tr>
				<tr>
				<td>石河子</td>
				</tr>
				<tr>
				<td>图木舒克</td>
				</tr>
				<tr>
				<td>乌鲁木齐</td>
				</tr>
				<tr>
				<td>五家渠</td>
				</tr>
				<tr>
				<td>阿克苏</td>
				</tr>
				<tr>
				<td>博尔塔拉</td>
				</tr>
				<tr>
				<td>伊犁哈萨</td>
				</tr>
				<tr>
				<td>吐鲁番</td>
				</tr>
				<tr>
				<td>喀什</td>
				</tr>
				<tr>
				<td>克孜勒苏</td>
				</tr>
				<tr>
				<td>塔城</td>
				</tr>
				<tr>
				<td>阿勒泰</td>
				</tr>
				<tr>
				<td>和田</td>
				</tr>
				<tr>
				<td>巴音郭楞</td>
				</tr>
				<tr>
				<td>昌吉回族</td>
				</tr>
				<tr>
				<td>哈密</td>
				</tr>
				</tbody></table>
				</div>
		</div>
</div>
</body>
</html>
