
package com.wrox.expertj2ee.ticket.boxoffice;

import java.io.Serializable;
import java.util.Date;

public interface Booking extends Serializable {

	/** Getter for property
	 * This method will be implemented by a subclass generated by the EJB container
	 * @return id persistent property
	 */
	String getAuthorizationCode();


	/** Getter for property
	 * This method will be implemented by a subclass generated by the EJB container
	 * @return dateMade persistent property
	 */
	Date getDateMade();


	Reservation getReservation();

} 
