CREATE TABLE "DANPIN_1217"."PRODUCT_LIST" 
   (	"SID" NUMBER, 
	"BRAND_SID" NUMBER NOT NULL ENABLE, 
	"PRO_CLASS_SID" NUMBER, 
	"PRO_SKU" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"PRO_WEIGHT_SID" NUMBER DEFAULT 26 NOT NULL ENABLE, 
	"PRO_DESC" VARCHAR2(160 CHAR), 
	"PRO_WRI_TIME" DATE, 
	"PRO_ACTIVE_BIT" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"PRO_SELLING" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"PRO_TYPE" NUMBER(1,0) DEFAULT 1, 
	"SEX_SID" NUMBER, 
	"AGE_SID" NUMBER, 
	"OCCASION_WEAR_SID" NUMBER, 
	"MATERIAL_STYLE_SID" NUMBER, 
	"SEASON_SID" NUMBER, 
	"WHICHYEAR" VARCHAR2(20 CHAR), 
	"PRODUCT_NAME" VARCHAR2(100 CHAR), 
	"OPT_USER_SID" NUMBER, 
	"OPT_REAL_NAME" VARCHAR2(40 CHAR), 
	"OPT_UPDATE_TIME" DATE, 
	"PRO_SELLING_TIME" DATE, 
	"MEMBERS_LEVEL_SID" NUMBER, 
	"PRODUCT_CLASS_SID" VARCHAR2(100 CHAR), 
	"PRODUCT_CLASS_DESC" VARCHAR2(500 CHAR), 
	"PRO_PAGE_DESC" CLOB, 
	"PRESENT_FLG" NUMBER(1,0) DEFAULT 0, 
	"ACTIVITY_FLG" NUMBER(10,0) DEFAULT 0, 
	 CONSTRAINT "PRODUCT_LIST_PK" PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 9437184 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DANPIN_IND"  ENABLE, 
	 CONSTRAINT "PRODUCT_LIST_U01" UNIQUE ("BRAND_SID", "PRO_SKU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 14680064 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DANPIN_IND"  ENABLE, 
	 CONSTRAINT "FK_PRODUCT_LIST_BRAND" FOREIGN KEY ("BRAND_SID")
	  REFERENCES "DANPIN_1217"."BRAND" ("SID") ENABLE, 
	 CONSTRAINT "FK_PRODUCT_LIST_PRO_CLASS" FOREIGN KEY ("PRO_CLASS_SID")
	  REFERENCES "DANPIN_1217"."PRO_CLASS_DICT" ("SID") ENABLE, 
	 CONSTRAINT "FK_PRODUCT_LIST_PRO_WEIGHT" FOREIGN KEY ("PRO_WEIGHT_SID")
	  REFERENCES "DANPIN_1217"."PRO_WEIGHT_DICT" ("SID") ENABLE, 
	 CONSTRAINT "FK_PRODUCT_LIST_SEX" FOREIGN KEY ("SEX_SID")
	  REFERENCES "DANPIN_1217"."CLASS_SEX" ("SID") ENABLE, 
	 CONSTRAINT "FK_PRODUCT_LIST_AGE" FOREIGN KEY ("AGE_SID")
	  REFERENCES "DANPIN_1217"."CLASS_AGE" ("SID") ENABLE, 
	 CONSTRAINT "FK_PRODUCT_LIST_OCCASION" FOREIGN KEY ("OCCASION_WEAR_SID")
	  REFERENCES "DANPIN_1217"."CLASS_OCCASION_WEAR" ("SID") ENABLE, 
	 CONSTRAINT "FK_PRODUCT_LIST_MATERIAL" FOREIGN KEY ("MATERIAL_STYLE_SID")
	  REFERENCES "DANPIN_1217"."CLASS_MATERIAL_STYLE" ("SID") ENABLE, 
	 CONSTRAINT "FK_PRODUCT_LIST_SEASON" FOREIGN KEY ("SEASON_SID")
	  REFERENCES "DANPIN_1217"."CLASS_SEASON" ("SID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 42991616 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DANPIN_DATA" 
 LOB ("PRO_PAGE_DESC") STORE AS (
  TABLESPACE "DANPIN_DATA" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));

CREATE INDEX "DANPIN_1217"."IN_CLASS" ON "DANPIN_1217"."PRODUCT_LIST" ("PRO_CLASS_SID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DANPIN_IND";

CREATE INDEX "DANPIN_1217"."IN_WEIGHT" ON "DANPIN_1217"."PRODUCT_LIST" ("PRO_WEIGHT_SID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 6291456 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DANPIN_IND";

CREATE INDEX "DANPIN_1217"."PRODUCT_LIST_INDEX1" ON "DANPIN_1217"."PRODUCT_LIST" ("PRO_SELLING_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DANPIN_IND";

CREATE UNIQUE INDEX "DANPIN_1217"."PRODUCT_LIST_PK" ON "DANPIN_1217"."PRODUCT_LIST" ("SID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 9437184 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DANPIN_IND";