/*
 * File: app/store/LatestMonths.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.LatestMonths', {
    extend: 'Ext.data.Store',
    requires: [
        'MyApp.model.MonModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'MyArrayStore',
            model: 'MyApp.model.MonModel',
            data: [
                {
                    name: '1月',
                    value: '1'
                },
                {
                    name: '2月',
                    value: '2'
                }
            ]
        }, cfg)]);
    }
});