/*
 * File: app/controller/AppCtrl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ex.controller.AppCtrl', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'btnes',
            selector: '#nav button'
        },
        {
            ref: 'test',
            selector: '#test1'
        },
        {
        	ref: 'tab',
            selector: '#tab'
        }
    ],



    onButtonClick: function(button, e, eOpts) {
        alert('click');
//        var view = Ext.widget('form1');
        alert(this);
        this.application.widget(this.getTabPanel(),"","form1","1");
//        Ext.getCmp('tab').add();
    },
    
    init: function() {
        this.control({
            "#cf": {
                click: this.onButtonClick
            }
        });
    }
    

});
