/*
 * File: app/controller/AppLaunchCtrl.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.AppLaunchCtrl', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'tabPanel',
            selector: '#tabPanel'
        },
        {
            ref: 'sampleTest',
            selector: '#sampleTest'
        },
        {
            ref: 'historyQuery',
            selector: '#historyQuery'
        },
        {
            ref: 'trendChart',
            selector: '#trendChart'
        },
        {
            ref: 'btns',
            selector: '#navi button'
        }
    ],

    onButtonAddClick: function(button, e, options) {
        this.unpressOtherBtns(button);
        this.application.widget(this.getTabPanel(), 'FormCtrl', 'MyForm', '1');
        //this.getTabPanel().setActiveTab(this.getSampleTest());
    },

    onButtonQryClick: function(button, e, options) {
        this.unpressOtherBtns(button);
        this.application.widget(this.getTabPanel(), 'QueryCtrl', 'MyQuery', '2');
        //this.getTabPanel().setActiveTab(this.getHistoryQuery());
    },

    onButtonChartClick: function(button, e, options) {
        this.unpressOtherBtns(button);
        this.application.widget(this.getTabPanel(), 'ChartCtrl', 'MyChart', '3');
        //this.getTabPanel().setActiveTab(this.getTrendChart());
    },

    unpressOtherBtns: function(exceptBtn) {
        var nextBtn = this.getBtns();
        while (nextBtn) {
            if (nextBtn.itemId !== exceptBtn.itemId && nextBtn.pressed) {
                console.log(nextBtn.itemId);
                nextBtn.toggle(true);
            }
            nextBtn = nextBtn.nextSibling("button");
        }

    },

    onControllerClickStub: function() {

    },

    init: function() {
        this.control({
            "#btnAdd": {
                click: this.onButtonAddClick
            },
            "#btnHistory": {
                click: this.onButtonQryClick
            },
            "#btnTrend": {
                click: this.onButtonChartClick
            }
        });

    }

});
