/*
 * File: app/controller/ChartCtrl.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.ChartCtrl', {
    extend: 'Ext.app.Controller',

    stores: [
        'MyChartStore',
        'LatestMonths'
    ],

    refs: [
        {
            ref: 'tabPanel',
            selector: '#tabPanel'
        },
        {
            ref: 'latestMon',
            selector: '#comboLatest'
        }
    ],

    onComboboxSelect: function(combo, records, options) {
        console.log('onComboboxSelect');
        this.getMyChartStoreStore().load();
        return false;
    },

    init: function(application) {
        this.control({
            "#comboLatest": {
                select: this.onComboboxSelect
            }
        });
        this.getMyChartStoreStore().on(
        {
            'load' : function(me, operation, eOpts) {
                me.loadData(generateData(8));
            }
        }
        );
        this.getLatestMon().setValue('1');
        this.getMyChartStoreStore().load();
    },

    onLaunch: function() {

    }

});
