/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    border: false,
                    height: 78,
                    html: '<iframe width="100%" height="100%" align="center" frameborder="0"></iframe>',
                    title: ''
                },
                {
                    xtype: 'panel',
                    region: 'west',
                    width: 150,
                    title: 'My Panel',
                    items: [
                        {
                            xtype: 'treepanel',
                            border: true,
                            height: 629,
                            id: 'menutree',
                            collapsible: true,
                            title: '菜单',
                            rootVisible: false,
                            viewConfig: {

                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    title: 'My Panel'
                }
            ]
        });

        me.callParent(arguments);
    }

});