/*
 * File: app/view/manage.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ex.view.manage', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    height: 72,
                    padding: 0,
                    bodyPadding: 0,
                    title: '',
                    items: [
                        {
                            xtype: 'image',
                            height: 201,
                            width: 201,
                            src: 'images/logo.png'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'west',
                    split: true,
                    itemId: 'nav',
                    width: 163,
                    bodyPadding: 20,
                    title: '菜单',
                    items: [
                        {
                            xtype: 'button',
                            height: 79,
                            itemId: 'cf',
                            margin: 5,
                            width: 97,
                            enableToggle: true,
                            iconAlign: 'top',
                            iconCls: 'add',
                            pressed: true,
                            scale: 'large',
                            text: '表单',
                            toggleGroup: 'menu'
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    region: 'center',
                    itemId: 'tab',
                    activeTab: 0
//                    items: [
//                        {
//                            xtype: 'panel',
//                            html: 'welcome to peking',
//                            title: '欢迎'
//                        }
//                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});