/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    border: false,
                    height: 30,
                    html: '<h1 align="center">网站后台管理应用</h1>',
                    title: ''
                },
                {
                    xtype: 'panel',
                    region: 'west',
                    width: 150,
                    title: '网站后台应用管理',
                    items: [
                        {
                            xtype: 'treepanel',
                            border: true,
                            height: 659,
                            id: 'menutree',
                            collapsible: true,
                            title: '菜单',
                            store: 'MyTreeStore',
                            rootVisible: false,
                            viewConfig: {

                            }
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    floatable: false,
                    region: 'center',
                    split: false,
                    splitterResize: false,
                    frame: true,
                    id: 'modelpanel',
                    focusOnToFront: false,
                    shadow: false,
                    toFrontOnShow: false,
                    autoDestroy: false,
                    detachOnRemove: false,
                    collapseFirst: false,
                    frameHeader: false,
                    header: false,
                    manageHeight: false,
                    deferredRender: false,
                    removePanelHeader: false
                },
                {
                    xtype: 'panel',
                    region: 'south',
                    frame: true,
                    height: 30,
                    html: '<p align="center"><span >Copyright (C) 2012 shopin All rights reserved; 本系统由上品折扣信息系统部提供技术支持</span></p>',
                    shadow: 'frame',
                    frameHeader: false,
                    title: ''
                }
            ]
        });

        me.callParent(arguments);
    }

});