/*
 * File: app/controller/AppCtrl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.AppCtrl', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'btns',
            selector: '#navi button'
        },
        {
            ref: 'test',
            selector: '#test1'
        }
    ],

    constructor: function(cfg) {
        cfg = cfg || {};
        this.callParent(this.processAppCtrl(cfg));
    },

    processAppCtrl: function(config) {
        return config;
    },

    onButtonClick: function(button, e, eOpts) {

        alert('click');
    },

    init: function(application) {
        this.control({
            "#btnAdd": {
                click: this.onButtonClick
            }
        });
    },

    onLaunch: function() {

    }

});
