/*
 * File: app/model/MonData.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.MonData', {
    extend: 'Ext.data.Model',
    alias: 'model.MonData',

    fields: [
        {
            name: 'name'
        },
        {
            name: 'data1'
        },
        {
            name: 'data2'
        },
        {
            name: 'data3'
        },
        {
            name: 'data4'
        },
        {
            name: 'data5'
        },
        {
            name: 'data6'
        },
        {
            name: 'data7'
        },
        {
            name: 'data8'
        },
        {
            name: 'data9'
        }
    ]
});